# fly.toml file generated for gitea-demo on 2022-05-17T12:36:56+01:00

app = "gitea-demo"

kill_signal = "SIGTERM"
kill_timeout = 5

[build.args]
  GITEA_URL="gitea-demo.fly.dev"

[env]
  LOG_LEVEL = "debug"
  PHX_HOST = "gitea-demo.fly.dev"
  PORT = "4000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
    
